steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'Clone'
  args: ['clone', 'https://github.com/Lavanya-nallu/game-of-life1.git']
- name: 'gcr.io/cloud-builders/mvn:3.3.9-jdk-8'
  args: ['install']
  dir: 'game-of-life/gameoflife-build/'
   # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/direct-mason-375505/test:v2", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/direct-mason-375505/test:v2"]


